---
- name: point inventory to primary
  import_playbook: tower_set_inventory_pm.yml

- name: obtain secret key value
  hosts: localhost
  gather_facts: no
  become: false
  vars_files: tower_vars.yml
  tasks:
    - name: obtain the SECRET_KEY value
      include_role:
        name: tower_secret_key
        tasks_from: pull.yml
      vars:
        tower_secret_key_delegate: "{{ groups['tower'][0] }}"

- import_playbook: tower_set_inventory_dr.yml

- name: deploy secret key standby cluster
  hosts: tower
  gather_facts: no
  vars_files: tower_vars.yml
  become: true
  tasks:
    - name: deploy secret key file
      include_role:
        name: tower_secret_key
        tasks_from: push.yml
      vars:
        tower_secret_key_value: "{{ hostvars.localhost.tower_secret_key }}"

    # adding this because installer fails this was left behind
    # and awx user and group was removed
    # - name: remove extraneous tower log directory
    #   file:
    #     path: /var/log/tower
    #     state: absent

- import_playbook: tower_set_inventory_pm.yml

- import_playbook: tower_setup_replication.yml

- import_playbook: tower_check_replication.yml
...