---
- name: setup inventory to point to disaster recovery site
  hosts: localhost
  become: false
  gather_facts: no
  vars_files: tower_vars.yml
  vars:
    _tower_failback: "{{ tower_failback | default(false) }}"
    _tower_inventory_file: "{{ tower_inventory_dr if not _tower_failback else tower_inventory_pm  }}"
  tasks:
    - name: "set inventory to {{ _tower_inventory_file }}"
      include_role:
        name: tower_inventory
      vars:
        tower_inventory_file: "{{ _tower_inventory_file }}"
...